### ISSUE TITLE
chore(ci): migrate to `nx-set-shas` action

### ISSUE THREAD

**Issue by edbzn** [rx-angular/rx-angular#978]
## Description

To run Nx affected commands in the CI I would suggest using [`nrwl/nx-set-shas@v2`](https://github.com/nrwl/nx-set-shas) instead of `nrwl/nx-tag-successful-ci-run@v1`.  The new action will fetch the git sha1 from the last successful CI run and allow us to use it for the affected comparison:  

```
nx affected:build --base="${{ env.NX_BASE }}"
```

This approach is cleaner since it avoids spamming tags in the repository.

**Comment by hoebbelsB** [comment]
we actually use both of those extensions, as proposed in the [nx docs](https://nx.app/docs/configuring-ci):

```yaml
- name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'

- name: Tag main branch if all jobs succeed
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: nrwl/nx-tag-successful-ci-run@v1
```
